const nodemailer = require("nodemailer")

const mailSender = async (email, title, body) => {
  try {
    let transporter = nodemailer.createTransport({
      host: process.env.MAIL_HOST,
      auth: {
        user: process.env.MAIL_USER,
        pass: process.env.MAIL_PASS,
      },
      secure: false,
    })

    let info = await transporter.sendMail({
      from: `"Wave Learn" <${process.env.MAIL_USER}>`, // sender address
      to: `${email}`, // list of receivers
      subject: `${title}`, // Subject line
      html: `${body}`, // html body
    })
    console.log(info.response)
    return info
  } catch (error) {
    console.log(error.message)
    return error.message
  }
}

module.exports = mailSender























































// const { default: mongoose } = require('mongoose');
// const nodemailer = require('nodemailer')

// const mailSender = async (email, title, body) => {
//     try {
//         let transporter = nodemailer.createTransport({
//             host: process.env.MAIL_HOST,
//             auth: {
//                 user: process.env.MAIL_USER,// your official appk email id 
//                 pass: process.env.MAIL_PASS // less secure password generated by the your google account
//             }
//         })

//         let info = await transporter.sendMail({
//             from: "WaveNotion || CodeWave-by Risu Gupto",// either put your email or any apk message and apk name
//             to: email,
//             subject: title,
//             html: body
//         })
//         console.log("email sent by the mailsender",info);
//         return info;
//     } catch (error) {
//         console.log("error occur in the mailsendin gphase",error.message)
//     }
// }

// module.exports=mailSender